### ISSUE TITLE
Installing on Big Sur and Monterrey

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/fontdiffenator#94]
Hi! When trying to install in Big Sur and Monterrey I got the following error. It works for me on Mojave.

```
Traceback (most recent call last):
  File "/Users/fercozzi/tools/bin/fontdiffenator", line 11, in <module>
    load_entry_point('fontdiffenator==0.9.12', 'console_scripts', 'fontdiffenator')()
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/pkg_resources/init.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/pkg_resources/init.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/pkg_resources/init.py", line 2443, in load
    return self.resolve()
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/pkg_resources/init.py", line 2449, in resolve
    module = import(self.module_name, fromlist=['name'], level=0)
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/diffenator/init.py", line 10, in <module>
    from diffenator.constants import FTHintMode
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/diffenator/constants.py", line 1, in <module>
    from freetype.raw import *
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/freetype/init.py", line 24, in <module>
    from freetype.raw import *
  File "/Users/fercozzi/tools/lib/python3.8/site-packages/freetype/raw.py", line 52, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found
```

I tried installing Freetype via brew and freetype-py via pip, both cases returns that freetype is already installed.

Thanks

**Comment by glenda-tn** [comment]
Hello. I have the same issue. Diffenator doesn't work for me on the M1 Mac, Monterey 12.5.1.
